### PR TITLE
Incorporate mabrek/alertlogic changes

### PR DESCRIPTION
**Pull request by nalundgaard**
- changes from mabrek/httpc
- fix gen_tcp:recv 64M limit
- make files UTF-8 compliant for Erlang 17/18+
- handle transfer-encoding correctly

### CODE REVIEW

**Comment by nalundgaard** [comment]
@motobob @juantascon can you guys have a look at this? to merge this atop esl I had to patch up the startup conflicts in the unit tests. I favored the R15+ method (using `application:ensure_all_started/1`)

**Comment by juantascon** [comment]
this pullrq fixes issues #57 and #48

**Comment by nalundgaard** [comment]
Oy, I made it to the wrong fork! This was meant to go to the public Alert Logic fork. I guess I will leave this PR here, but I will make another one to the correct place.

**Comment by nalundgaard** [comment]
I am going to go ahead and close this, actually. While these fixes do seem a good idea, given that this repo is abandoned, our company will just use a fork of it with these changes (and removal of legacy support for pre-R16 Erlangs). See alertlogic/lhttpc#2.

**Pull request closed without merging**
